pipeline_name: "crypto_coincap"
url: "https://api.coincap.io/v2/assets"
params:
  limit: 50
data_key: "data"
output_path: "raw/crypto"
schema:
  id: "string"
  symbol: "string"
  name: "string"
  priceUsd: "float64"
  marketCapUsd: "float64"