pipeline_name: "open_food_facts"
url: "https://world.openfoodfacts.org/api/v2/search"
params:
  countries_tags_en: "argentina"
  page_size: 50
data_key: "products"
output_path: "raw/food_products"
schema:
  code: "string"
  product_name: "string"
  brands: "string"
  ecoscore_score: "float64"
  nutriscore_score: "float64"